- name: variables
  hosts: local
  connection: local
  vars: 
    name: "SHIVA"
    times: 3000TIMES
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "i love {{ name }}, this may times {{ times }}"
