- name: dynamic variables
  hosts: local
  connection: local
  vars_prompt:
  - name: NAME
    promt: enter the name 
    private: false
  vars_files:
  - course.yaml
  tasks:
  - name: print dynamic variables
    ansible.builtin.debug:
      msg: "variable {{ NAME }}, EXPERIANCE {{ EXP }}, skills {{ SKILL }}, MAPPI {{ MAPPING }}"

