- name: Install Nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL
    when: ansible_os_family == "RedHat"
    ansible.builtin.dnf:
      name: docker
      state: installed

  - name: install nginx if Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"